services:
    nginx:
        build:
            context: .
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - auth
            - users
            - urls
        networks:
            - internal

    users:
        build:
            context: .
            dockerfile: apps/users/Dockerfile
        environment:
            - NODE_ENV=developtment
            - URLS_API=http://urls/3002/urls
            - AUTH_API_PORT=http://auth:3003/auth
            - JWT_SECRET=salt
            - EXPIRES_IN=5m
            - BCRYPT_SALT=10
            - SQLITE_SYNCHRONIZE=true
        volumes:
            - ./volumes/users:/app/db
        networks:
            - internal

    urls:
        build:
            context: .
            dockerfile: apps/url_shortener/Dockerfile
        environment:
            - NODE_ENV=developtment
            - USERS_API=http://users:3001/users
            - AUTH_API_PORT=http://auth:3003/auth
            - JWT_SECRET=salt
            - EXPIRES_IN=5m
            - BCRYPT_SALT=10
            - SQLITE_SYNCHRONIZE=true
        volumes:
            - ./volumes/urls:/app/db
        networks:
            - internal

    auth:
        build:
            context: .
            dockerfile: apps/auth/Dockerfile
        environment:
            - NODE_ENV=developtment
            - USERS_API=http://users:3001/users
            - JWT_SECRET=salt
            - EXPIRES_IN=5m
            - BCRYPT_SALT=10
            - SQLITE_SYNCHRONIZE=true
        volumes:
            - ./volumes/auth:/app/db
        networks:
            - internal

networks:
    internal:
        driver: bridge
