services:
    nginx:
        build:
            context: .
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - auth
            - users
            - urls
        networks:
            - internal

    users:
        build:
            context: .
            dockerfile: apps/users/Dockerfile
        volumes:
            - ./volumes/users:/app/db
        env_file: '.env.docker'
        networks:
            - internal

    urls:
        build:
            context: .
            dockerfile: apps/urlShortener/Dockerfile
        volumes:
            - ./volumes/urls:/app/db
        env_file: '.env.docker'
        networks:
            - internal

    auth:
        build:
            context: .
            dockerfile: apps/auth/Dockerfile
        volumes:
            - ./volumes/auth:/app/db
        env_file: '.env.docker'
        networks:
            - internal

networks:
    internal:
        driver: bridge
